### ISSUE TITLE
[Feature] Implement side bar in a grouped route layout that holds the `chats` and `feed` page

### ISSUE THREAD

**Issue by RashJrEdmund** [Vanessa082/in-touch#27]
_See Next docs to further understand what I mean in the header by [`grouped routes`](https://nextjs.org/docs/app/building-your-application/routing/route-groups)_

- ShadCn does a good Job at providing us components. One of their newest components is the `SideBarComponent`
head on to [their docs](https://ui.shadcn.com/docs/components/sidebar) and implement a sidebar for us.

The sidebar should be in a place just as described by this issue's topic 👆🏽

Get inspired by `X's` sidebar and implement the fields in our design

![Screenshot 2024-11-03 at 11 12 25](https://github.com/user-attachments/assets/35b38bc8-9a85-4ed7-bc03-6588e325f4b9)

### Navigation

Add the following navigators to the sidebar (using the `Link tag` from NextJs)

- [x] My feed
- [x] Chats
- [x] Notifications
- [x] Profile
- [x] Settings
and finally
- [x] A user button at the bottom of the side bar just as twitter does
![Screenshot 2024-11-03 at 11 16 49](https://github.com/user-attachments/assets/b87c603e-75a3-41a3-b240-e51d45cf63a3)

**Comment by Vanessa082** [comment]
I thought this is done @RashJrEdmund

**Comment by RashJrEdmund** [comment]
Yh, It is
